### PR TITLE
WIP: Add regressions for windows

### PR DESCRIPTION
**Pull request by themperek**
Initial work to run windows regression with docker on travis.

To speed up may create an image (at librecores?)
Related to #659 
Should rather try to run with conda?

### CODE REVIEW

**Comment by imphil** [comment]
Uh, I didn't know travis can do Windows (I always see people using AppVeyor for that.) Speaking of which, would that be an alternative to test different Python versions at the same time?

In addition to those general remarks, I think this needs a rebase on top of the now-merged Travis changes.

**Comment by stuarthodgson** [comment]
Seems fine to me after a rebase.

**Comment by imphil** [comment]
In addition to rebasing, could you split the changes into two commits, one for the travis stuff, and one for the changed Makefiles (which are independent of the CI changes).

**Comment by themperek** [comment]
Close in favor of #877

**Pull request closed without merging**
