### PR TITLE
Improve performance by avoiding calling logging.getLogger unless something is actually being logged

### PR DESCRIPTION
**Pull request by eric-wieser**
This:
* Adds a `lazy_property` decorator, to handle computing expensive attributes the first time they're used.
* Hides all `SimLog` instance behind a lazy_property. This is especially important for the Trigger, coroutine, and RunningCoroutine objects which are constructed and destroyed the most frequently.
* Hides the only guaranteed call to `.log` behind the same `COCOTB_SCHEDULER_DEBUG` environment variable, to avoid paying for a logger for every coroutine.

For a very contrived test-case of the following, this brought the runtime from ~10s to ~7.5s (Python 2.7):

```python
import cocotb
from cocotb.triggers import Timer, RisingEdge, First
from cocotb.clock import Clock

@cocotb.test()
def test1(dut):
    clk_gen = cocotb.fork(Clock(dut.clk, 100).start())
    for i in range(10000):
        yield [RisingEdge(dut.clk), Timer(200)]
```

### CODE REVIEW

**Comment by eric-wieser** [comment]
For our `test_cocotb`, noting that performance across CI runs is probably not a great metric: [before: 2.33s](https://travis-ci.org/potentialventures/cocotb/jobs/550988333#L2261), [after, 1.75s](https://travis-ci.org/potentialventures/cocotb/jobs/551183858#L2106)

**Comment by stuarthodgson** [comment]
Are these changes reverting a regression that came in as a result of more logging being added or just a good optimization anyway? If the latter then there has still been quite a drop in performance.

**Comment by imphil** [comment]
This improvement is good to take, but it's not directly addressing the regressions reported in #961. 

As @ andresdemski  reported in #961:

> I tried #967 . The performance is improved a 10% but still far from the best performance

So let's take this, and continue investigating. 10% is a nice improvement.

**Comment by imphil** [comment]
On the code itself: This looks rather work-around-ish, but I'm fine with that for now. Ideally, we'd only pay a small, one-time setup cost for a logger singleton (once per simulation run), and have calls to disabled log classes being close to a no-op (e.g. log.debug with debug disabled). 

But for now I'm fine with taking this, and looking after a "real" solution in a follow-up. I've opened #969 for that.

**Comment by eric-wieser** [comment]
@stuarthodgson: part of the performance change is due to scheduler internals were replaced with internal coroutines and events, which thanks to the logging were more expensive than I expected.

So while this doesn't directly revert anything, the offending changes made this a hotter path than it used to be.

**Pull request merged**
