### PR TITLE
Issue382

### PR DESCRIPTION
**Pull request by stuarthodgson**
@luked80 

Sorry for the delay in this but finally done.

@leftink Any chance you can test the FLI interface?

### CODE REVIEW

**Comment by leftink** [comment]
@stuarthodgson 
I checked out your branch and it looks like it fixes the problem described in Issue #382.

I noticed, thought that this only seems to address the time reported in the Log.  Is there going to be any follow on work such that when specifying the time to Timer() and period to Clock() that we have a standard way to set that to be resolution independent.  There is still the problem with this branch that with the following statement:

`cocotb.fork(Clock(dut.clk, 2500).start())`

The value 2500 is still dependent on the resolution set in the simulator, i.e. could mean 2.5ns or 2.5us, etc.  It would be nice to get this updated to specify an actual "time", i.e. 2500ps, and let cocotb translate that to appropriate time.

**Comment by stuarthodgson** [comment]
@leftink , yes their will be. The original scope of #382 was reporting of time. But now their is a way to get the simulator view of time via simulator.get_sim_precision() the follow on work can happen.

**Comment by leftink** [comment]
@stuarthodgson I noticed that you used vhpiResolutionLimitP property to get the resolution.  Have you tested this on IUS?  Looking at the version of IUS I have, that property isn't even listed in the vhpi_user.h file.  It seems like we may still need to use vhpiPrecisionP at least for IUS.

**Comment by stuarthodgson** [comment]
@leftink I'm using IUS 15.1, I can get values out but they are possibly wrong, however due to a quick of IUS and cocotb since libvpi.so is always loaded this ends up being used as the source for the time. 

I'll have a look at the vhpiPrecisionP though.

**Comment by leftink** [comment]
@stuarthodgson Hopefully, when I can get some time to look into IUS.  We can worry about the precision problem when/if we ever get IUS to run without VPI.

**Pull request merged**
