### PR TITLE
End Of Simulation Summary and Support for Simulation Time

### PR DESCRIPTION
**Pull request by leftink**
This request adds a few features:
- Updates Timer() and Clock() to support a "units" parameter as discussed in #458 
- Add the ability through an environment variable to suppress some of the logging information.  Setting the variable COCOTB_REDUCED_LOG_FMT will hide some of the formatted columns to allow more of the Data column to fit on the screen.
- Adds two banners that are printed at the end of the simulation.  One is a summary of the of all the tests that were run and highlights any that failed.  The second is a total simulation summary.  There are corresponding metrics printed that I have found useful in the past.

Below is an example of the banners and the suppressed logging information.  I forced a test failure to demonstrate the highlighting.

banner

### CODE REVIEW

**Comment by leftink** [comment]
@stuarthodgson and @chiggs 

I am sure you guys are busy, but when you have a second could you look at the  seg-fault that is occuring with Python 3 only.  I am unable to test with iVerilog.  None of the additional changes shouldn't care between Python2 and Python3.  The only one I can think of is the change to the Makefile I made which reversed the search order for the python-config files, but that shouldn't have broke it.  I tested in my environment with Questa and Python 3.5.1 and everything was fine.

**Comment by chiggs** [comment]
@leftink I really like this change :+1: thanks for this.

I'll try and look into the Travis failure - shouldn't be a sim problem if it works on Python2, it's possible this has uncovered a latent issue that was simply masked.

**Comment by elgorwi** [comment]
@leftink,

Could you explain the benefit of copying modelsim.ini in commit d2eeba5ab59448b80173f62741e959871b02bd7d?

Thanks!

**Comment by leftink** [comment]
@elgorwi The reason had to do with some installs at or company that for some reason had remapped work to other folders and our installs are read only.  By copying the modelsim.ini, I can then map the library appropriately since the copied ini file will be used first.  Is this causing a problem for you?

**Comment by leftink** [comment]
@chiggs and @stuarthodgson 
I need to fix some colouring issue in the message banner so that is what these latest updates are.

I finally setup an environment at home so I could look into the python3 version seg-faulting with Icarus.  Unfortunately I will have to leave that in your court to investigate.  I am running Ubuntu, with the latest daily build of Icarus, and python 3.5.2 and I don't see any seg-faults.  If there is anything I can do to help investigate this let me know.

**Comment by leftink** [comment]
@chiggs and @stuarthodgson 
I managed to get to the root of the problem causing the seg-faults and it had nothing to do with the changes and looks to be an issue you had tried to resolve before where the wrong "python-config" is being found on the system.

Let me start by saying I reversed the search order for the python config to have the following priority for the Linux environment:
1.  pythonX.Y-config  (where X.Y is the major/minor versions, e.g. 3.4 or 2.7)
2.  pythonX-config  (where X is the major version, e.g. 2 or 3)
3.  python-config

I reversed the order because our systems have multiple versions of python installed causing it to find python-config (a 2.x version) since the python3 versions only had a python3-config.  This reversed order search should ensure the correct python config is found.

Now, for the root of the issue with travis, it appears the wrong version of python-config is being found and used in both the 2.7 and 3.4 versions of the builds.  In all cases, it is finding and using the python-config (for 2.7) and python3-config (for 3.4) in the location "/usr/bin".  Below is some logging information I added to the makefile and you can see the versions being used for the 2.7 configuration.

```
172"***         PY_CFG_EXE: python2.7-config"
173"***            PY_LIBS: -lpthread -ldl -lutil -lm -lpython2.7"
174"***             PY_VER: 2.7"
175"***             PY_MAJ: 2"
176"***             PY_MIN: 7"
177"***             PYTHON: /home/travis/virtualenv/python2.7.12/bin/python"
178"***      PYTHON-CONFIG: /usr/bin/python-config"
179"*** PYTHON<MAJ>-CONFIG: /usr/bin/python2-config"
180"*** PYTHON<VER>-CONFIG: /usr/bin/python2.7-config"
181"*** PYTHON3.4.4-CONFIG: "
```

I believe the only reason there hasn't been an issue with the 2.7 configuration, is the version installed in "/usr/bin/" is close enough to the 2.7.x version that is actually being used.  However, the version in "/usr/bin/" for python3 is only at 3.2 which is definitely not compatible with the 3.4 environment you are trying to run.

The reason it broke recently is the command in travis file to link the python3-config into the virtual environment is pointing to 3.4.2 and it looks like the new version is 3.4.4.  Perhaps there needs to be a more robust method to get to the python-config file for linking into the virtual environment and technically, it should do the same thing for 2.x configuration as well just to ensure the correct libraries are linked against.

I have updated the paths for now and it fixed the issue so these changes are ready to merge.

**Pull request merged**
