### PR TITLE
Don't require SPHINX_BUILD to import packages

### PR DESCRIPTION
**Pull request by imphil**
*Note: This is the first of a series of preparatory PRs to get #517 merged. I'm trying to split out all not strictly related commits to make sure we run all the tests and are able to back out individual parts as needed. @themperek please double-check the commit messages and let me know if they are wrong/misleading or too short to explain the change in sufficient detail.*

Previously, the SPHINX_BUILD environment variable was required to import
the cocotb packages without the corresponding simulation extensions
being present. This behavior breaks when documenting code, e.g. with
Sphinx, but it also breaks when creating a cocotb package, as setuptools
rely on introspection of the package.

This commit turns things around: In the default case, cocotb can be
imported without the simulator extensions. Only if COCOTB_SIM is set,
the simulator extensions are being included as well.

In all simulator Makefiles we now set COCOTB_SIM.

### CODE REVIEW

**Comment by eric-wieser** [comment]
> as setuptools
rely on introspection of the package

I'm not sure I agree with this rationale. Setuptools should not be trying to import the package it's installing.

Change is probably a good idea anyway though.

**Comment by themperek** [comment]
@eric-wieser Some things are loaded in `__init__.py` so always.  We want to have a script like `cocotb-config` (that does not require simulator) this need to change.

**Comment by imphil** [comment]
@themperek Ah ok, so the motivation for this change (apart from sphinx) is cocotb-config, not setuptools? Then I'll update the commit message in this regard.

**Comment by themperek** [comment]
@imphil Both. Setup tools will try to make executable and import cocotb (this will fail) also calling cocotb-config would fail (for this would be a workaround to set `SPHINX_BUILD` but this is ugly).

**Comment by imphil** [comment]
I wasn't really able to reproduce the setuptools/distutils case, always importing the simulator library doesn't cause `setup.py sdist` or `setup.py bdist` to fail on Python 2.7 or 3.7. Anyways, it's not really a critical whether we have two or three reasons to do this change. I've updated the commit message to not state false facts, and will merge this after Travis completes.

**Pull request merged**
