### PR TITLE
Multi layer triggers

### PR DESCRIPTION
**Pull request by putsplut**
Addresses the issue noted in issue #520.  There are problems with a trigger attempting to prime/unprime other triggers, which is required for triggers such as ClockCycles - specifically related to modifying the callback of an already primed trigger or being unable to set a different (specialized) callback because the trigger is already primed.  This patch addresses the issue by creating the concept of helper functions which are registered with the scheduler along with a list of triggers which should activate the helper function.  This is analogous to coroutines providing a list of triggers.  I refer to these helper-based triggers as multi-layer triggers because they rely upon other (sub) triggers.

The multi-layer triggers allow for more than just ClockCycles.  For example, it is possible to specify a Sequential trigger as 
yield Sequential(ClockCycles(clk, 5), RisingEdge(valid), FallingEdge(valid), ClockCyles(12))
which would trigger only after each of the sub triggers has occurred in turn.

### CODE REVIEW

**Comment by luked80** [comment]
@putsplut Would be great if you could add some test cases for these new features?

**Comment by putsplut** [comment]
Will do.  Still new at this flow.

**Comment by putsplut** [comment]
Additional testing revealed some problems.  I will try again once I've cleaned up some issues.

**Comment by stuarthodgson** [comment]
Its a promising idea though.

**Pull request closed without merging**
