### PR TITLE
Implement abstraction layer for ANSI colors.

### LINKED ISSUE #684: ANSI color codes should not be hardcoded
Depending on the terminal's background color, some of Cocotb's strings may be hard to read.
Cocotb should internally use abstracted color names like ``ANSI.ERROR_FG`` instead of ``ANSI.CYAN_FG``which could then be customized in a single file.

(If we wanted to get fancy, we could even allow to choose between different color themes.)

### PR DESCRIPTION
**Pull request by cmarqu**
Fixes #684.

### CODE REVIEW

**Comment by lukedarnell** [comment]
So to change the colours one would edit the ANSI.py ?

**Comment by cmarqu** [comment]
For now, yes. This needs some discussion about how to make it user friendly.

**Comment by cmarqu** [comment]
One way could be:
```
try:
    import ANSI_local
except:
    pass

try:
    import ANSI_user
except:
    pass
```

**Comment by lukedarnell** [comment]
Editing ANSI.py sounds like a great start.

**Pull request merged**
