### PR TITLE
Fixes #267: Removes dependency on simulator radix setting when...

### LINKED ISSUE #267: Driving a Binary String through the FLI is dependent on simulator settings
In the function, FliImpl.cpp::set_sign_value(std::string &value), the call to mti_ForceSignal() passes a string representing the values for every position in the vector.

Apparently, in Mentor's infinite wisdom, the interpretation of that string through this interface is dependent on the "radix" that is set for that signal, or if not set, the global (default) radix.

In my case I was trying to drive a 32-bit std_logic_vector, and by default our "radix" is set to hex, and to my surprise the value driven into the signal was the last 8-bits of the string treated as a 32-bit hex string.

The only solution to this problem, that would let me drive a std_logic_vector with values other than 0 and 1, was to modify the string format.  The following are some examples of the string format:
    string = "8'b01101000"
    string = "10'bZ1XU000011"

I tested the solution using the FLI interface in Questa.

### PR DESCRIPTION
**Pull request by leftink**
… sending binary string

### CODE REVIEW

**Comment by chiggs** [comment]
@leftink thanks for making the changes.  I'll leave this for @stuarthodgson to merge.

@stuarthodgson I think your comments demonstrate that we're overdue for a review and cleanup of the existing codebase!

**Comment by stuarthodgson** [comment]
Quite agree. I think its out of my head after 6 months i might stand a chance of spotting things now.

**Comment by leftink** [comment]
@stuarthodgson I was just curious if there are any other issues with this. I have more changes coming that are in these same files and dependent on these changes.

**Comment by stuarthodgson** [comment]
@leftink  Sorry for the delay, been busy adding some new features.

**Pull request merged**
