### PR TITLE
Clean-up some issues introduced by dev_array pull

### PR DESCRIPTION
**Pull request by leftink**

### CODE REVIEW

**Comment by leftink** [comment]
@chiggs and @stuarthodgson 
With my updates to the BinaryValue to raise a ValueError when bits aren't able to be resolved, test issue_142 now fails.  I updated the test to expect an error for icarus so that the regression can pass.

The failure is interesting because I believe the way BinaryValue used to behave was actually masking this failure.  The failure is caused because the stream_in_data_wide is 64-bits all with the value 'Z'.  The old BinaryValue would have resolved this to be the integer 0, which would allow it to pass since the first test is to set it to zero.

I don't have access to Icarus in my environment so I can't look into this further, but I believe the issue has always been there and just masked.

**Comment by stuarthodgson** [comment]
@leftink Sorry for the delay in merging this.

**Comment by themperek** [comment]
I see large (x4) slowdown after those changes (https://travis-ci.org/SiLab-Bonn/fe65_p2/builds).
The problems seems to be somewhere in this function: 
https://github.com/potentialventures/cocotb/blob/master/cocotb/handle.py#L227
Any idea?

**Comment by leftink** [comment]
@themperek my first thought/question, are you accessing deprecated handle attributes a lot in your code?  This would be things like handle.name or handle.log.  If so, try updating to use the non-deprecated names, i.e. Handle._name and handle._log.  The biggest change in this area was to change the search order to look for valid HDL names in the simulator before checking the deprecated name list. This was necessary because otherwise valid HDL names were inaccessible through cocotb. 

Just a thought.

**Comment by themperek** [comment]
@leftink Thank you the _log was a good hint (https://github.com/SiLab-Bonn/basil/commit/6bd60a369c4eccf5ae34a7ec794203c2d251e0c8).
Maybe a warning would be nice to have on this issue.

**Comment by leftink** [comment]
@themperek  Actually if you look at the top of your log you will see a warning printed once.  I believe they were trying to avoid filling up the log with a bunch of warnings.

**Comment by themperek** [comment]
Mea culpa

**Pull request merged**
