### PR TITLE
Update io.c

### PR DESCRIPTION
**Pull request by tachwali**
Fix io.c file  to work for python 3 by using PyInit_io_module instead of initio_module

### CODE REVIEW

**Comment by imphil** [comment]
You don't really need the `moduledef` part. How about:

```diff
diff --git a/examples/endian_swapper/cosim/io.c b/examples/endian_swapper/cosim/io.c
index 917f0d1..8e74ad9 100644
--- a/examples/endian_swapper/cosim/io.c
+++ b/examples/endian_swapper/cosim/io.c
@@ -113,14 +113,24 @@ int IOWR(unsigned int base, unsigned int address, unsigned int value)
     return 0;
 }
 
-PyMODINIT_FUNC
-initio_module(void)
+#if PY_MAJOR_VERSION >= 3
+    #define MOD_INIT(name) PyMODINIT_FUNC PyInit_##name(void)
+#else
+    #define MOD_INIT(name) PyMODINIT_FUNC init##name(void)
+#endif
+
+MOD_INIT(io_module)
 {
     PyObject* io_module;
     io_module = Py_InitModule("io_module", io_module_methods);
     if (!io_module) {
-        printf("Failed to load io_module\n");
-        exit(1);
+#if PY_MAJOR_VERSION >= 3
+        return NULL;
+#else
+        return;
+#endif
     }
+#if PY_MAJOR_VERSION >= 3
+    return io_module;
+#endif
 }
```

**Comment by imphil** [comment]
@eric-wieser I have a half-working patch to get these tests running in CI, I hope I can post it soonish.

**Comment by eric-wieser** [comment]
Another neat trick you can use here is:
```C
#if PY_MAJOR_VERSION >= 3
    #define MOD_RETVAL(x) x
    #define MOD_INIT(name) PyMODINIT_FUNC PyInit_##name(void)
#else
    #define MOD_RETVAL(x)
    #define MOD_INIT(name) PyMODINIT_FUNC init##name(void)
#endif
```
Used as:
```C
MOD_INIT(io_module) {
    PyObject* io_module;
    io_module = Py_InitModule("io_module", io_module_methods);
    return MOD_RETVAL(io_module);
     }
 }
```

**Comment by tachwali** [comment]
Thanks for the feedback. 
Are we expecting me to apply the suggested changes? If so, let me know so I can do it and we can then merge this PR

**Comment by imphil** [comment]
> Are we expecting me to apply the suggested changes?

Yes, that's how this typically works: during review people suggest improvements, and you're then asked to incorporate those changes into your branch (which automatically updates the PR here on GitHub). 

For this PR I did the changes for you and updated your branch.

**Pull request merged**
