### PR TITLE
Accumulated fixes and features

### PR DESCRIPTION
**Pull request by chiggs**
First of all apologies for a couple of things - the accumulation of many features globbed into a single PR and the length of time this has taken to raise.  In summary there are a bunch of fixes and features that have been added on a private development and this PR brings them back upstream.  Once these are harmonised with upstream, we're hoping that with the help of other developers the future of Cocotb will be more distributed and democratic as per some of the discussions that have been ongoing in various locations.

Here is a high-level overview of the changes:

* Improve support for arrays and structures on various simulators and expand testing
* Fix non-determinism in external (requires adding knowledge of threading executors to scheduler)
* Introduce the concept of `COCOTB_HOOKS` which can be added before tests run, allowing for example automated instantiation of protocol checkers in the design or Python based models
* Introduce `COCOTB_RESOLVE_X` to select how to handle X values on sampling
* Add `simulator.get_definition_name` and `simulator. get_definition_file` APIs to query simulator, for example to enable improved error messages to be produced
* Avoid going down to the simulator to fetch current time by caching the time in each callback

cc @leftink @luked80 @jeremyherbert @stuarthodgson @themperek @wallento etc

### CODE REVIEW

**Comment by luked80** [comment]
Awesome!
Will try and get our own set of updates working on top of this.
And feedback any issues/patches.

**Comment by themperek** [comment]
I have checked new version with our development and it looks ok  There seems to be some problem with normal unit tests?

**Comment by TC01** [comment]
I figured I'd give this branch a test (and then hopefully start using it, with a few other pending changes, for our verification work!). Using Icarus 10, a slightly old version now, I got the following unit test failure, which seems to be the same as what Travis complained about.

```
   12.41ns INFO     cocotb.regression                         regression.py:307  in execute                         Running test 8/26: test_clock_with_units
   12.41ns INFO     ..t_clock_with_units.0x7fce6ce16950       decorators.py:203  in send                            Starting test: "test_clock_with_units"
                                                                                                                    Description: None
   12.41ns INFO     cocotb.sample_module                     test_cocotb.py:167  in test_clock_with_units           Created clock >Clock(1.0 MHz)<
   12.41ns INFO     cocotb.sample_module                     test_cocotb.py:172  in test_clock_with_units           Created clock >Clock(250.0 MHz)<
 2012.41ns WARNING  ..t_clock_with_units.0x7fce6ce16950       decorators.py:215  in send                            Expected a period of 1 us
 2012.41ns ERROR    cocotb.regression                         regression.py:286  in handle_result                   Test Failed: test_clock_with_units (result was TestFailure)
```

However, when I modified test_clock_with_units to print out the observed period (printing out the difference between edge_time_ns and start_time_ns [here](https://github.com/chiggs/cocotb/blob/pending/tests/test_cases/test_cocotb/test_cocotb.py#L190)):

```
    if edge_time_ns != start_time_ns + 1000:
        raise TestFailure("Expected a period of 1 us, instead got %f ns" % (edge_time_ns - start_time_ns))
```

I got the following, which I guess suggests it's just a floating point rounding problem in Python and not actually an issue with cocotb.

```
Expected a period of 1 us, instead got 1000.000000 ns
```

**Comment by forensicgarlic** [comment]
i don't know why it might be necessary, but this change gets through the travis linking error for the python 3 tests: https://github.com/potentialventures/cocotb/pull/576/commits/6c4320ee732b2af11faee17de57b9f40a4a5662c

**Comment by stuarthodgson** [comment]
This needs merging and there are fixes waiting for the issues that will result so I'm going to go ahead and merge then fixup the two issues.

**Pull request merged**
