### PR TITLE
Isinstance performance

### PR DESCRIPTION
**Pull request by eric-wieser**
Previously this did the equivalent of:
```python
if isinstance(x, D):
   x = C(x)
if isinstance(x, C):
   x = B(x)
if isinstance(x, B):
   x = A(x)
if isinstance(x, A):
   return x
raise TypeError
```
This is extremely inefficient, as after the first branch is taken all future isinstance checks will return true, but not before the expensive operation of walking the `__mro__`

We could transforms the above to:
```python
if isinstance(x, D):
   return A(B(C(x))
if isinstance(x, C):
   return A(B(x))
if isinstance(x, B):
   return A(x)
if isinstance(x, A):
   return x
raise TypeError
```
However, this is a little fragile to maintain. This compromises on introducing a chain of functions that call each other, and still succeeds in not calling `isinstance` once a match is found.

One consequence of this change is that the scheduler does not sanity check that `Waitable._wait` methods are correct. I think that's ok, because those are primarily for internal use anyway, and it would be better to validate those once at start rather than each time.

---

Note to @imphil: This is deliberately two commit to make the optimization vs refactor a little more obvious - I think it would be better _not_ to squash-merge

### CODE REVIEW

**Comment by eric-wieser** [comment]
xref #961

**Comment by nevsan** [comment]
Why not also change your `if` statements to `elif` for even more improvement?

**Comment by imphil** [comment]
@nevsan the function returns early, the else wouldn't get executed.

**Comment by nevsan** [comment]
I see. I missed that--thought there was more going on after the conversion.

**Comment by andresdemski** [comment]
* eric-wieser:isinstance-performance : 21873.56 NS/S
* current master (cache-triggers): 21413.66 NS/S
* prev cache-triggers:  20667.17 NS/S

performances improvement: (isinstance-performance / prev cache-triggers) = ~6%

**Comment by imphil** [comment]
LGTM, with one question: what is is that is slow? Is `isinstance` slow itself? Would it be faster to have a variable inside the classes we use telling us the type? E.g. introduce a `_type` variable in the classes we care about, and do something like

```
try:
    if result._type == 'trigger':
       ...
except ...
```

(Not that I like that approach, but I'd like to understand the performance considerations a bit more.)

**Comment by eric-wieser** [comment]
I can't comment on the speed of `isinstance`, but from the profiling graph it was clear it used up a significant fraction of the scheduler time.

If you want to go down that path, a better approach would be adding an `__cocotb_trigger__` method to those objects - essentially moving each of my functions into a "magic" method.

**Comment by imphil** [comment]
I'd love to experiment a bit more here, but I'm currently a bit short on time. So I'll take this as a strict improvement; we can always do more in the future.

**Pull request merged**
