### PR TITLE
Add python packaging for cocotb

### PR DESCRIPTION
**Pull request by imphil**
After all the preliminary stuff merged and didn't seem to cause much trouble here's now the final commit series to add packaging to cocotb. 

Please review and test (especially with the "old" way of running cocotb in your existing setup!). It should still be possible to use cocotb as before.

### CODE REVIEW

**Comment by imphil** [comment]
I'll leave this open over the weekend for people to give feedback and merge on Monday.

**Comment by tmeissner** [comment]
Is there any info about the "new" way of running cocotb? Is this related to install cocotb with pip?

**Comment by imphil** [comment]
@tmeissner There are no docs yet (I've filed https://github.com/potentialventures/cocotb/issues/837 for that). But in the end it's `pip install` and then use `cocotb-config` instead of setting the `COCOTB` environment variable (see the tests for how to use `cocotb-config` in your Makefiles).

**Comment by themperek** [comment]
@imphil I have tested the package and there is a mistake.
Missing here: https://github.com/potentialventures/cocotb/pull/836/files#diff-97c91a104c431d0c365565d3ac03ac13R1 (line 1)
should be: `recursive-include cocotb/share *.c* *.h Makefile.* Makefile`
missing `Makefile` at the end. 

Can you correct?

**Comment by imphil** [comment]
Thanks, I've fixed that.

**Comment by themperek** [comment]
You can try `pip install cocotb==1.2.dev1`

One can get the path in the Makfile to COCOTB with $(shell cocotb-config --share) (no need to set COCOTB environment variable).

**Comment by imphil** [comment]
This is now merged. Let's see if it sticks.

**Pull request merged**
