### PR TITLE
adding simulator that support _ARGS options according to grep Makefile.*

### PR DESCRIPTION
**Pull request by Martoni**
Issue #994 :
Adding simulator that support Options COMPILE_ARGS and SIM_ARGS.

### CODE REVIEW

**Comment by imphil** [comment]
Thanks for this PR @Martoni! Looking at the list: is there a compiler that *doesn't* support SIM_ARGS and COMPILE_ARGS? If not, we can simply remove the list completely.

**Comment by Martoni** [comment]
Two simulators makefile doesn't have *_ARGS macro : modelsim and xcelium.

**Comment by Martoni** [comment]
I think we can safely remove the list completely in fact.

**Comment by cmarqu** [comment]
We can actually hand over ``COMPILE_ARGS`` and ``SIM_ARGS`` to ``irun``/``xrun`` too and it will take care to give them to the correct "sub-tool".

**Comment by imphil** [comment]
OK, so let's take this PR as it is and file follow-up issues to the two options supported on cadence and modelsim for feature parity. @cmarqu would you mind creating those issues?

**Pull request merged**
