### PR TITLE
Make coroutines documentable with autodoc/Sphinx

### PR DESCRIPTION
**Pull request by imphil**
Currently it is impossible to add API documentation to functions
decorated with @cocotb.coroutine: the __doc__ string is always taken
from the decorator, not from the documented function itself. This
behavior is mentioned in the autodoc documentation:

> Note
>
> If you document decorated functions or methods, keep in mind that
> autodoc retrieves its docstrings by importing the module and
> inspecting the __doc__ attribute of the given function or method.
> That means that if a decorator replaces the decorated function with
> another, it must copy the original __doc__ to the new function.
>
> From Python 2.5, functools.wraps() can be used to create well-behaved
> decorating functions.

-- http://www.sphinx-doc.org/en/stable/ext/autodoc.html

As mentioned in the documentation, using functools to wrap the required
attributes resolves the issue.

### CODE REVIEW

**Comment by imphil** [comment]
The travis run failed most likely due to a infra issue at the travis side, please retrigger to see correct results.

**Comment by forensicgarlic** [comment]
this change will get the travis python 3 tests to run: https://github.com/potentialventures/cocotb/pull/576/commits/6c4320ee732b2af11faee17de57b9f40a4a5662c

**Comment by stuarthodgson** [comment]
@imphil once we have travis back and the conflict is resolved this looks good to merge.

**Comment by forensicgarlic** [comment]
travis is back up and running now, is this on deck to be merged @stuarthodgson ?

**Pull request merged**
