### PR TITLE
Fix avl bugs

### PR DESCRIPTION
**Pull request by Martoni**
I had some bugs using avalon driver. Here a fix proposal.

### CODE REVIEW

**Comment by forensicgarlic** [comment]
Is there a testcase you can add that shows this change passes where the original didn't?

**Comment by chiggs** [comment]
I’m not convinced about this change - do you have a definite test case?

On the whole NextTimeStep shouldn’t be required in a monitor or driver

**Comment by Martoni** [comment]
Uh is a really old code. I'm not sure to be able to find the original test case.

**Comment by imphil** [comment]
@Martoni Thanks for your contribution, and sorry it took so long. I'm closing this PR for now, but please re-open if you find the test case for these changes, it would be good to fully understand why these changes are necessary before we merge.

**Pull request closed without merging**
