### PR TITLE
Issue #115 : functionality to specify simulation delays in time units

### PR DESCRIPTION
**Pull request by luked80**

### CODE REVIEW

**Comment by jeremyherbert** [comment]
Hi Luke,

Have you considered an implementation/function like this? (untested and not really polished, I just wrote this off the top of my head now)

```
def is_subset_or_equal(superset, subset):  ## this is builtin for python3, not sure about python2
    for key in subset:
        if key not in superset:
            return False

ranges = {"s": 1, "ms": 1e-3, "us": 1e-6, "ns": 1e-9, "ps": 1e-12, "fs": 1e-15}
def gen_time(**kwargs):
    assert is_subset_or_equal(ranges.keys(), kwargs) # make sure there is nothing silly going on

    counts = 0
    for r in ranges:
        counts += int(round((kwargs[r] * ranges[r]) / 1e1**sim_precision))
    
    return counts


### usage
yield Timer(gen_time(ms=5, ns=800))  # wait for 5.0008 ms
```

could also be done with named keyword arguments, like

```
def gen_time(s=0, ms=0, us=0, ns=0, ps=0, fs=0):
```

**Comment by luked80** [comment]
@jeremyherbert Not sure I follow.
Why not just do:
```python
yield Timer(ns(10.001))
```

**Comment by jeremyherbert** [comment]
I just thought it might be easier than importing a function for each range, and using a loop instead of several functions removes the duplicated code.

`from cocotb.sim_time import gen_time`

instead of

`from cocotb.sim_time import s, ms, us, ns, ps, fs`

I think that `from cocotb.sim_time import *` is generally frowned upon too, because the programmer begins to pollute the global namespace.

You could also do `gen_time(ns=10.001)` 

I've also found in the past that one letter functions tend to be confusing, as that namespace generally seems to be reserved for iteration (`for i in range(...)`, `for k in dict.keys()`, `for s in strings`, etc) 

I don't have anything wrong with the way that it is, just suggesting possible alternatives :)

**Comment by leftink** [comment]
@luked80 one thing I noticed because it has bit me, you might want to add protection around importing the simulator like in other places.  The reason is when generating document ion with Sphinx the simulator module doesn't exist.

**Comment by leftink** [comment]
@luked80 and @jeremyherbert 
I have thought more about this, and personally I am not sure what either of you have proposed is the right approach.  The approach you have proposed would be most beneficial for maintaining backwards compatibility.  In my humble opinion, which would require updates for everyone, would be to update the Timer and the Clock modules to take a Float value, representative of seconds.  It would look something like:
```python
Timer(1.0)      #Create a 1 second timer
Timer(10.0e-9)  #Create a 10 ns timer
```

@stuarthodgson or @chiggs may have a strong desire to maintain backwards compatibility in which case your solution is a good one.

**Comment by jeremyherbert** [comment]
@leftink I personally think that it should always be transformed to integer/fixed point, as a floating points can be tricky to deal with in their rounding. It doesn't really matter with the `time.sleep` function, because I don't think there are any python applications that have such hard real-time constraints (the interpreted nature kind of prevents that). 

For example, if you did a delay by 1.31 seconds Timer(s(1.31)), the double precision representation is 1.309309999942779541 which means you have an error of almost 700 microseconds. 

I think that ideally, the entire system should be represented using the [Decimal module]( https://docs.python.org/3/library/decimal.html) using the precision of the simulator.

**Comment by luked80** [comment]
@leftink I like your suggestion.
But as you say, @chiggs and @stuarthodgson would need to approve this approach, as it would break backwards compatibility.
Are there any other functions that would need to be updated to make this approach consistent across cocotb?
Testbench code using ```cocotb.clock ``` would need to be updated.
I can't think of any other core cocotb functions or testbench code that would need updating.


@jeremyherbert I think ns, ps, fs, etc look nicer:
```python
yield Timer(ns(10))
```
vs
```python
yield Timer(gen_time(ns=10))
```
But do take your point on ```sim_time.s```
I will change that to ```sim_time.sec```

There is a bunch of duplicated code in each function.
I will try and figure out a way to create the functions without duplicating the code.

**Comment by leftink** [comment]
@jeremyherbert You actually have the wrong value when looking at the actual representation of 1.31 as a double precision value.  The value you showed is the value you get after casting single precison to double precision.  1.31 in pure double precision is 1.31000000000000005329070518201 (0x3FF4F5C28F5C28F6) which is accurate to below the resolution of any simulator.  What python maps a "float" to is normally double precision, but I don't believe that is a requirement.

@luked80 There is a way this could be done to maintain backwards compatibility and allow for a float or even a decimal value as suggested by @jeremyherbert .  In the Timer() and Clock(), the argument could be tested using isinstance(arg, float), isinstance(arg, decimal.Decimal) and if either is true, use the Precision to convert to an integer value to pass to the simulator, otherwise, assume the argument is an integer that should be passed through, as it is today.

**Comment by luked80** [comment]
@leftink Are you suggesting the behaviour for these two statements would be different:
```
yield Timer(1.)
yield Timer(1)
```

**Comment by leftink** [comment]
@luked80 yes those two statements would be treated differently, but that is to maintain backwards compatibility with what I would consider a deprecated interface use.  A warning could be provided like for the deprecated attributes on the handle class. Ideally everyone would migrate to the float,string, or decimal versions over time.

**Comment by luked80** [comment]
@leftink that seems really confusing to me. 
And could be a source of subtle bugs.
I'd either prefer one or the other.

@chiggs @stuarthodgson Can we get some guidance here on which way this is going to go?

**Comment by stuarthodgson** [comment]
To chime in a bit. I think that it is important to retain the backwards compatibility such that ```Timer(1)``` is a single time step. I agree it was wrong from the start but do worry about breaking the world for people. So I would lean towards ```Timer(ns(x.y))``` where x.y is a double. The handling of this and setting of the real delta being done in the ```Timer()``` class based on the sim precision.

I've never really had a handle on how many people use clock rather than driving theselves but the interface here would also need changing as an int as period no longer seems sufficient.

**Comment by leftink** [comment]
I think of everything discussed, I like @chiggs suggestion the best.

**Comment by nicklfitz** [comment]
Sorry to come a little late to this discussion.
I think that the original suggestion of @leftink gives the cleanest interface.  Times are specified in seconds, and precision is specified in a way that is well understood in science/engineering and also natively supported by Python (e.g `10e-9` for 10 ns).

In order to solve the backward compatability problem perhaps a new class, derived from Timer, could be considered.  This new class would always take an input time in seconds, and convert it to simulation timesteps as required.  It could also accept a `units` named argument to accommodate those who prefer `ns` to `e-9` (for example).
```python
Timer(1)  # Single simulation timestep
RealTimer(10e-9)  # 10 ns
RealTimer(10, units='ns')  # Also 10 ns
RealTimer(1.0)  # 1 s
RealTimer(1)  # Also 1 s
```
I have suggested `RealTimer` as the name of the new class; `RTimer` might be considered for brevity.  But maybe there are better options.
This approach, of creating a new class/function rather than adding and complicating input arguments, has precedent in Python; the example that comes to mind is `range` and `xrange`.

**Comment by leftink** [comment]
@luked80, @chiggs , and @stuarthodgson 
I have submitted a solution to this that matches the solution proposed by @chiggs.  I didn't update any tests or examples to use the "units", but did add two  additional tests to check the functionality for Clock() and Timer().   581d462 has the changes in them.  Let me know your thoughts.

**Comment by luked80** [comment]
@leftink Looks good to me. Thanks for implementing.

**Comment by leftink** [comment]
@luked80 Looks like my Pull Request made it in.  If it works for you then maybe this can be closed.

**Comment by stuarthodgson** [comment]
This was implemented via PR #474

**Pull request closed without merging**
