### PR TITLE
Add support for Cadence Xcelium, based on the existing IUS support.

### PR DESCRIPTION
**Pull request by cmarqu**

### CODE REVIEW

**Comment by lukedarnell** [comment]
@cmarqu Is xcelium providing the same level of functionality as ius?

**Comment by cmarqu** [comment]
It does. Xcelium is basically just a rebranding of Incisive unless you enable the multi-core feature which then uses a different simulator core (which I haven't used yet).

**Comment by cmarqu** [comment]
Well, only in terms of features and internals it is "just" a rebranding, but Xcelium has different names for most of its binaries, some command line options, and also other file and directory names it produces, so a new Makefile is needed, yes.

**Comment by mciepluc** [comment]
@cmarqu is there really need for a separate makefile, or could it be done more nicely - e.g. makefile.xcelium calling makefile.ius. As both makefiles looks very similar, it should be a bit more compact way.

**Comment by nevsan** [comment]
The way we do it is to check for the existence of `xrun` in the path (e.g. `which xrun`) and then make any required modifications based on that. It's only a few small places that might need an update, so I would agree it may not be worth an entirely new Makefile.

**Comment by cmarqu** [comment]
While a merge between the ``ius`` and ``xcelium`` Makefile could be done, I'm not sure it's worth the added complexity. Other than is the case with Questa and Modelsim (one is a thin wrapper around the other in cocotb), Incisive is not going to be kept supported in parallel to Xcelium, it is replaced by it. So I would just let the existing ``Makefile.ius`` become irrelevant as time progresses, and do improvements to the new ``Makefile.xcelium`` without having to care for backward compatility. (One such improvement would be to replace the ``c``part in ``access +rwc`` with ``-createdebugdb`` which is a more performant replacement, but not available in older Incisives, but in all Xceliums).
That said, I don't care too much and rather look forward to #696.

**Comment by themperek** [comment]
@cmarqu Makefile location has changed. Can you change this?

**Comment by cmarqu** [comment]
@themperek Makefile location is now updated, thanks for spotting.

**Pull request merged**
