### PR TITLE
Enforce that no new flake8 violations are added

### PR DESCRIPTION
**Pull request by eric-wieser**
This takes the current flake8 failures, adds them to a whitelist, and turns on flake8 actually failing if new violations are detected.

Some of these are outright bugs which are not caught by tests. I'll do some follow-ups to fix some of these problems.

### CODE REVIEW

**Comment by imphil** [comment]
Thanks! I'm actually open to reformatting the whole tree with yapf or a similar tool once we have added a coding style to the docs (Google or pep8 seem the obvious choices)

**Comment by eric-wieser** [comment]
The motivation is more about the non-style violations, like "invalid escape sequence" or "undefined name"

**Comment by eric-wieser** [comment]
That and the fact I was surprised to see the flake8 step that runs on every CI run can never fail

**Comment by imphil** [comment]
Thanks, that's a good step forward.

**Comment by themperek** [comment]
https://github.com/potentialventures/cocotb/issues/879

**Pull request merged**
