### PR TITLE
Make 'bits' an accessible property of BinaryValue

### PR DESCRIPTION
**Pull request by oligu**
Prevents using of constructs like len(BinaryValue.binstr)

### CODE REVIEW

**Comment by forensicgarlic** [comment]
this looks good. Got any tests for the change? 

If you merge imphil:travis-lcci-image then travis will start passing again.

**Comment by forensicgarlic** [comment]
something easy like this seems worth adding: 
```diff
diff --git a/tests/test_cases/test_cocotb/test_cocotb.py b/tests/test_cases/test_cocotb/test_cocotb.py
index 1982cff..9780323 100644
--- a/tests/test_cases/test_cocotb/test_cocotb.py
+++ b/tests/test_cases/test_cocotb/test_cocotb.py
@@ -632,6 +632,13 @@ def test_binary_value(dut):
     """
 
     vec = BinaryValue(value=0,bits=16)
+    dut._log.info("Checking accessing bits")
+    if vec.bits != 16:
+        raise TestFailure("bits aren't getting set correctly")
+    vec.bits = 17
+    if vec.bits != 17:
+        raise TestFailure("bits aren't getting updated correctly")
+    
     dut._log.info("Checking default endianess is Big Endian.")
     if not vec.big_endian:
         raise TestFailure("The default endianess is Little Endian - was expecting Big Endian.")
```

**Comment by stuarthodgson** [comment]
@oligu as @forensicgarlic a testcase for this would be good, else it will wait for me to write one and then merge it.

**Comment by forensicgarlic** [comment]
My second comment has a simple test case. Would you want something more than that, @stuarthodgson ?

**Comment by forensicgarlic** [comment]
@stuarthodgson just pinging this issue again, anything more than the test I included above necessary?

**Comment by imphil** [comment]
I agree with @eric-wieser  that the naming `bits` is confusing, but is part of the constructor and hence should stay for backward-compat reasons. Having the same name all over the class is at least consistent.

**Comment by imphil** [comment]
Since we didn't hear back from @oligu I've opened #713 superseding this PR and adding the tests.

@oligu if you are still around I'd be happy if you could have a look at the updated PR and comment on it. Thanks!

**Pull request closed without merging**
