### PR TITLE
Fix for issue #583 : cleanup axi_lite_slave example to work in python 3 and 2

### PR DESCRIPTION
**Pull request by forensicgarlic**
with travis not currently working, it's a little harder to make sure I didn't break anything else, but with only 1 change not in the examples directory (that makes python 2 and 3 work, though less efficiently in 2) I think it should be safe.

### CODE REVIEW

**Comment by jrpetrus** [comment]
I noticed `iteritems()` in 4 places -- take a look at my PR #590?

**Comment by forensicgarlic** [comment]
That's a good point -- I was just looking for points where the example failed and didn't apparently fix all the potential problems. Did you spot these via a test failure of some sort, or just inspection? If a test failure, it'd be worth trying to incorporate a simple test into the regression.

**Comment by jrpetrus** [comment]
I caught it once in my own testbench and then did a global search:
```
find ./cocotb -name '*.py' | xargs grep iteritems -n
```

**Comment by stuarthodgson** [comment]
@forensicgarlic this seems to have been pulled in with the docker image changes, can this be closed?

**Comment by forensicgarlic** [comment]
yep, closing it is fine.

**Pull request closed without merging**
