### PR TITLE
Introduction of requirements tracking feature

### PR DESCRIPTION
**Pull request by svancau**
Add support for basic requirement tracking

Generates a by requirement summary as well as a JSON report containing each requirement and the test status

### CODE REVIEW

**Comment by ilesser** [comment]
This feature seems very interesting!

Could you give some more detail on how it works?

**Comment by stuarthodgson** [comment]
@svancau This is a prime example of a feature that should have an issue opened and some level of discussion about it, even if you think that delays things. Personally I feel this sort of feature is out of the scope of cocotb. I maybe alone on that though.

Such work though should also include

* Documentation on how to use it
* Examples of how to use it
* A running testcase

**Comment by cmarqu** [comment]
@imphil Should we have a GitHub label like "category:extension-module" for cases like this?

**Comment by imphil** [comment]
Thanks for your contribution @svancau! I'm sorry it took a while (or even more than that), but as you might have seen we're slowly picking up pace again. The backlog is not completely cleared yet, but we'll get there in a not too distant future.

I'm closing this PR for now, as the code most likely needs serious changes after we agree on an implementation method in the associated issue. The code stays around in this PR as reference, let's first have a discussion on the implementation method in #556.

**Pull request closed without merging**
