### PR TITLE
Added kwargs to Monitor functions.

### PR DESCRIPTION
**Pull request by jeinstei**
#830 

Added **kwargs to monitor classes. Not sure if we want the base class to accept kwargs.

### CODE REVIEW

**Comment by themperek** [comment]
It is OK. 
I may not understand something but what is a use-case for this?

**Comment by jeinstei** [comment]
It's just a convenience update that is a minimal change. When writing child classes, it is nice to be able to pass args and kwargs up to the parent without worrying about what arguments the parent accepts. This allows for consistent super().__init__ calls for drivers and monitors.

Whether or not the lowest-level base class should have the same is a philosophy question though-- how explicit should calls to such parents be?

**Comment by themperek** [comment]
You always know what is the parent.  Sorry but I do not see much usability here.

**Comment by imphil** [comment]
I'm rather neutral on that one, but let's ask the person who's most deeply rooted in the Python community: @eric-wieser does that PR sound sensible or would you propose another solution?

**Comment by eric-wieser** [comment]
I'm with @themperek here. I don't see the use case, and this will mask bugs of people pass the wrong arguments.

**Comment by imphil** [comment]
Thanks Eric, preventing bugs from passing wrong arguments is a very good reason not to do this change. @jeinstei since this was a convenience-only PR, I guess you're not blocked on this one and we can close it based on this discussion?

**Comment by eric-wieser** [comment]
I assume this can be closed, since #830 was too?

**Comment by imphil** [comment]
As I said in the issue, please re-open if the current behavior blocks you in some way.

**Comment by jeinstei** [comment]
Sounds great to me. I prefer clear arguments being passed in, as long as consistency holds across the project. Appreciate the discussion.

**Pull request closed without merging**
